version: '3.7'

services:
  db:
    container_name: "mysql_db"
    build:
      context: .
      dockerfile: mysql.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "secret"
    command:
      - --default-authentication-plugin=mysql_native_password